- name: mytests3playbook
  hosts: localhost
  become: 'yes'

  roles:
    - { role: ec2create, inst_name: "ansible-test-instance2", inst_class: "t3.small" }
  tasks:
    - name: 'checking connection via ping'
      action: ping

    - name: Print the output
      debug:
        msg: "The IP is {{ ec2.instances[0].private_ip_address }}"
    
    - name: Add new instance to host group
      add_host: hostname={{ ec2.instances[0].private_ip_address }} groupname=suvitg
      with_items: ec2.instances

- name: newplaybook
  hosts: suvitg
  become: 'yes'

  roles:
    - swinstall