- name: mytests3playbook
  hosts: localhost
  become: 'yes'

  tasks:
    - name: 'checking connection via ping'
      action: ping

    - name: start an instance with a public IP address
      amazon.aws.ec2_instance:
        region: us-east-1 
        name: "ansible-test-instance"
        key_name: "DevOps_Lab"
        vpc_subnet_id: subnet-060c1f8bcdbb27356
        instance_type: t3.small
        security_group: DevOps_Bastion_SG
        network:
          assign_public_ip: true
        image_id: ami-0b0dcb5067f052a63
        tags:
          Environment: Testing
      register: ec2

    - name: Print the output
      debug:
        msg: "The output is {{ ec2 }}"
    
    - name: Add new instance to host group
      add_host: hostname={{ ec2.instances[0].private_ip_address }} groupname=launched
      with_items: ec2.instances

- name: newplaybook
  hosts: launched
  become: 'yes'

  tasks:
    - name: 'checking connection via ping'
      action: ping

    - name: 'install unzip'
      yum:
        name: unzip
        state: latest
        
    - name: 'create directory'
      file:
        path: /home/ec2-user/testdir
        owner: ec2-user
        group: ec2-user
        mode: 0777
        state: 'directory'