- name: 'install unzip'
  yum:
    name: unzip
    state: latest

- name: 'create directory'
  file:
    path: /home/ec2-user/testdir
    owner: ec2-user
    group: ec2-user
    mode: 0777
    state: 'directory'